apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
      test: test-label
  template:
    metadata:
      name: second-app
      labels:
        app: second-app
        test: test-label
    spec:
      containers:
        - name: first-app-image
          image: shykhovmyron/first-app:2
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
      restartPolicy: Always

