apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort:  8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
      test: test-label
  template:
    metadata:
      name: second-app
      labels:
        app: second-app
        test: test-label
    spec:
      containers:
        - name: first-app-image
          image: shykhovmyron/first-app:2
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

